# Generated by Django 4.1.1 on 2022-09-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('answer_date', models.DateTimeField()),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='survey.surveyquestionalternative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='survey.surveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='survey.survey')),
            ],
            options={
                'ordering': ['answer_date'],
            },
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='alternatives',
            field=models.ManyToManyField(related_name='alternatives', to='survey.surveyquestionalternative'),
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='survey.surveyquestion'),
        ),
    ]
